version: '3.7'
services:

  falskcon:
    container_name: 'flaskcon'
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: 'mysqlcon'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123'
      MYSQL_DB: 'devops'

  mysqlcon:
    container_name: 'mysqlcon'
    image: 'mysql:latest'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'devops'
    volumes:
      - my-volume:/var/lib/mysql


  phpmyadmin:
    image: 'phpmyadmin:latest'
    ports:
      - "8080:80"
    environment:
      PMA_HOST: 'mysqlcon'
      MYSQL_ROOT_PASSWORD: '123'
    depends_on:
      - mysqlcon


volumes:
  my-volume:

